[workspace]
members = ["crates/emulator-core", "crates/emulator-wasm", "crates/qemu-emery", "crates/sifli-board"]
resolver = "2"
exclude = ["vendor/rp2350-emu"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/huntrontrakkr/pebble-browser-emulator"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[patch.crates-io]
rp2350-emu = { path = "vendor/rp2350-emu" }
