// Generated by scripts/optics/bake.py from explicit, unmeasured assumptions.
export const TIME2_OPTICS = {
  id: 'time2-layered-v1',
  calibration: 'unmeasured-assumptions',
  path: 'optics/time2-v1-0c5f3bbdd1c8.rgba',
  sha256: '0c5f3bbdd1c8c40dfed1e23425bece6735774e3162af0e5b6220bd492567aa23',
  bytes: 278528,
  width: 272,
  height: 256,
  angles: 32,
  glassIor: 1.52,
  glassRoughness: 0.12,
  recipeSha256: '45361ca50b86db6788c7384b87f41fb2bf1eb2a12c2059cd2c4123f714b25f84',
} as const;
